name: ci

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install Rust toolchain
        run: rustup show
      - name: Install cargo-deny
        run: cargo install cargo-deny --version 0.19.7 --locked
      - run: cargo xtask ci
